import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./provider";
import ContextProvider from "./context/ContextProvider";
// import ThemeToggle from "./ui/ThemeToggle/ThemeToggle";
import QueryProvider from "./context/QueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>
          <ContextProvider>
            <Providers>
              {/* <ThemeToggle /> */}
              {children}
            </Providers>
          </ContextProvider>
        </QueryProvider>
      </body>
    </html>
  );
}

